### ISSUE TITLE
Adding Wayfair OSPO members to private GitHub OSPO discussion membership

### ISSUE THREAD

**Issue by natalisucks** [community/OSPO#14]
Hi team,

Natali here, Wayfair's OSPO lead, and it was great to meet many of you at GitHub Universe in San Fransisco last week. I wanted to sign up myself and my team to the private OSPO Discussion Forum in order share and grow our well of knowledge in this space. See below for the required usernames:

- Natali Vlatko [@natalisucks]
- Dan Rowe [@draco2003]
- Lelia Bray-Musso [@lelia]
- Gary White Jr. [@GaryPWhite]

We're looking forward to chatting more about our OSPO work and helping GitHub empower more OSPOs in the ecosystem! 🚀

**Comment by ahpook** [comment]
@natalisucks invites sent! thanks for the ping.
